---
title: "Hyperthyroidism"
author: "Luis A. Figueroa, Paola Pazmiño, et al."
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile),'/README.md')) })
output: github_document
---
<i> Analysis and visualization developed by [Luis A. Figueroa](https://twitter.com/LuisFig1706) </i>

The purpose of this site is to make our meta-analysis as transparent as possible. All information or documents used, from the protocol to the final publication, will be available here. If further information is needed, please do not hesitate to contact us.

```{r setup, include=FALSE}
library(metafor)
library(tidyverse)
library(forestplot)
library(rmarkdown)
library(openxlsx)

knitr::opts_chunk$set(fig.path = "Figures/", dev='svg')
```



```{r functions_md&or, echo=FALSE, message=FALSE, warning=FALSE}
md <- function(database){
  
  db <- database
  db <- escalc(measure="MD", 
               m1i=mean_post1, m2i = mean_post2, 
               sd1i  = sd_post1, sd2i = sd_post2, 
               n1i = n1, n2i= n2, data=database)
  db$vi <- ifelse(is.na(db$vi), 
               ((db$mdul_post-db$mdll_post)/((2*abs(qt(0.05/2, db$total-1)))^2)), db$vi)
  db <- db[order(db$yi),]
  db <- summary(db)
  
  db$md <- paste(formatC(db$yi, format='f', digits =1)," ",
                 "(",formatC(db$ci.lb, format='f', digits =1),
                 ",",formatC(db$ci.ub, format='f', digits=1),")") 
  db$postmean1 <- paste(formatC(db$mean_post1, format='f', digits=1),'(', formatC(db$sd_post1, format='f', digits=1),')')
  db$postmean2 <- paste(formatC(db$mean_post2, format='f', digits=1),'(', formatC(db$sd_post2, format='f', digits=1),')')
  
  ma <- rma(yi, vi, measure='MD', data=db, method='REML')
  
  db$w <- paste(formatC(weights(ma), format='f', digits = 1),'%')
  db$weights <- weights(ma)
  
  list(pre = db, ma = ma)
}


table_md <- function(analysis, nstudies, int, comp, outcome, col, 
                     follow=FALSE){
   ifelse(nstudies>1,
        (b <- cbind( 
          c("Author", analysis$pre$author, 
            paste("Overall Mean Difference for", analysis$ma$k, "studies"),
            paste("(Tau^2 = ", (formatC(analysis$ma$tau2, digits=2, format="f")), ", df = ", 
                  (analysis$ma$k - analysis$ma$p),
                  ", p ", (ifelse(analysis$ma$QEp < 0.001, 
                                  paste("< 0.001"),
                                  paste("= ", formatC(analysis$ma$QEp, digits=3, format="f")))),
                  "; ", "I^2", " = ", (formatC(analysis$ma$I2, digits=1, format="f")), "%)")),
        c(paste(int), analysis$pre$n1, sum(analysis$pre$n1),NA),
        c(paste(outcome, '\n', col), analysis$pre$postmean1, NA, NA),
        c(paste(comp), analysis$pre$n2,sum(analysis$pre$n2), NA),
        c(paste(outcome, '\n', col), analysis$pre$postmean2, NA, NA),
        c("Mean Difference (95% CI)", analysis$pre$md, 
            paste(formatC(analysis$ma$b, format='f', digits =1), 
                  " (",formatC(analysis$ma$ci.lb, format='f', digits=1),
                  ",", formatC(analysis$ma$ci.ub, format='f', digits=1), ")"), NA),
        c("Weight (%)", analysis$pre$w, NA, NA))),
        (b <- cbind( 
        c("Author", analysis$pre$author),
        c(paste(int), analysis$pre$n1),
        c(paste(outcome,'\n', col), analysis$pre$postmean1),
        c(paste(comp), analysis$pre$n2),
        c(paste(outcome, '\n',col), analysis$pre$postmean2),
        c("Mean Difference (95% CI)", analysis$pre$md))))

  ifelse(follow==TRUE, 
          b <- cbind(b, c(paste('Follow-up'), analysis$pre$followup, NA)), NA)
  ifelse(follow==TRUE,
          b <- b[,c(1,ncol(b),2:(ncol(b)-1))], NA)
  
  
  b <- as_tibble(b) 
  b <- b %>% add_row(.before = 2)
  b <- b %>% add_row(.before = 2)
  b <- b %>% add_row(.after = nrow(b))
  
  ifelse(nstudies>1, b <- b %>% add_row(.before = nrow(b)-2), NA)

  
  ifelse(nstudies > 1,
        (c <- structure(list(
          mean = c(rep(NA, 3), analysis$pre$yi, NA, analysis$ma$b,NA, NA),
          lower = c(rep(NA, 3), analysis$pre$ci.lb, NA, analysis$ma$ci.lb, NA, NA),
          upper = c(rep(NA, 3), analysis$pre$ci.ub, NA, analysis$ma$ci.ub, NA, NA)),
          .Names = c("mean", "lower", "upper"),
          row.names = c(NA, -1L*nrow(b)),
          class = "data.frame")),
        (c <- structure(list(
          mean = c(rep(NA, 3), analysis$pre$yi, NA),
          lower = c(rep(NA, 3), analysis$pre$ci.lb, NA),
          upper = c(rep(NA, 3), analysis$pre$ci.ub, NA)),
          .Names = c("mean", "lower", "upper"),
          row.names = c(NA, -1L*nrow(b)),
          class = "data.frame")))

  c <- as_tibble(c)
  
  list(b = b, c = c)
} 


or <- function(database){
  db <- database
  db <- escalc(measure="OR", ai=e1, ci=e2, n1i=n1, n2i=n2,data=database)
  db <- db[order(db$yi),]
  db <- summary(db)
  
  db$est <-  exp(db$yi)
  db$ci.lb <- exp(db$ci.lb)
  db$ci.ub <- exp(db$ci.ub)
  
  
  db$rate1 <- paste(db$e1,"/",db$n1)
  db$rate2 <- paste(db$e2,"/",db$n2)
  db$or <- paste(formatC(db$est, format='f', digits =2)," ",
                 "(",formatC(db$ci.lb, format='f', digits =2),
                 "-",formatC(db$ci.ub, format='f', digits=2),")")  
  
  ma <- rma(db$yi, db$vi, measure='OR', data=db, method='REML')
  exp <- predict(ma, transf = transf.exp.int)
  
  db$weights <- weights(ma)
  db$w <- paste(formatC(db$weights, format='f', digits = 1),'%')
  
  
  list(pre = db, ma = ma, exp = exp)
}



table_or <- function(analysis, int, comp, outcome, nstudies){
  ifelse(nstudies>1,
  b <- cbind( 
    c("Author", analysis$pre$author, 
      paste("Overall Odds Ratio for", analysis$ma$k, "studies"),
      paste("(Tau^2 = ", (formatC(analysis$ma$tau2, digits=2, format="f")), ", df = ", 
            (analysis$ma$k - analysis$ma$p),
            ", p ", (ifelse(analysis$ma$QEp < 0.001, 
                            paste("< 0.001"),
                            paste("= ", formatC(analysis$ma$QEp, digits=3, format="f")))),
            "; ", "I^2", " = ", (formatC(analysis$ma$I2, digits=1, format="f")), "%)")),
    c(paste(int, '\n', outcome,'/','total n'),
      analysis$pre$rate1, paste(sum(analysis$pre$e1), " / ", sum(analysis$pre$n1)), NA),
    c(paste(comp, '\n', outcome,'/', 'total n'),
      analysis$pre$rate2, paste(sum(analysis$pre$e2), " / ", sum(analysis$pre$n2)), NA),
    c("Odds Ratio (95% CI)", analysis$pre$or, 
      paste(formatC(analysis$exp$pred, format='f', digits =2), 
            " (",formatC(analysis$exp$ci.lb, format='f', digits=2),
            "-", formatC(analysis$exp$ci.ub, format='f', digits=2), ")"), NA),
    c("Weight(%)", paste(formatC(weights(analysis$ma), format='f', digits = 1),'%'), NA, NA)),
       b <- cbind( 
        c("Author", analysis$pre$author),
        c(paste(int, '\n', outcome,'/','total n'),analysis$pre$rate1),
        c(paste(comp, '\n', outcome,'/', 'total n'),analysis$pre$rate2),
        c("Odds Ratio (95% CI)", analysis$pre$or)))
  
  b <- as_tibble(b, .name_repair = "unique")
  b <- b %>% add_row(.before = 2)
  b <- b %>% add_row(.before = 2)
  b <- b %>% add_row(.after = nrow(b))  
  
  ifelse(nstudies>1, b <- b %>% add_row(.before = nrow(b)-2), NA)

  
  ifelse(nstudies > 1,
        (c <- structure(list(
          mean = c(rep(NA, 3), analysis$pre$est, NA, analysis$exp$pred,NA, NA),
          lower = c(rep(NA, 3), analysis$pre$ci.lb, NA, analysis$exp$ci.lb, NA, NA),
          upper = c(rep(NA, 3), analysis$pre$ci.ub, NA, analysis$exp$ci.ub, NA, NA)),
          .Names = c("mean", "lower", "upper"),
          row.names = c(NA, -1L*nrow(b)),
          class = "data.frame")),
        (c <- structure(list(
          mean = c(rep(NA, 3), analysis$pre$est, NA, NA),
          lower = c(rep(NA, 3), analysis$pre$ci.lb, NA, NA),
          upper = c(rep(NA, 3), analysis$pre$ci.ub, NA, NA)),
          .Names = c("mean", "lower", "upper"),
          row.names = c(NA, -1L*nrow(b)),
          class = "data.frame")))

  c <- as_tibble(c)
  
  list(b = b, c = c)
} 
  

```

```{r dichotomous_analysis, echo=FALSE, include=FALSE}
# Ca 19-9 > 37
data1 <- read.xlsx("Ca 19-9.xlsx")
data_ca <- data1[,-9] 
names(data_ca) <- c("author", "int", "comp", "outcome", "n1", "n2", "e1", "e2")
data_ca$author[2] <- "Keane., et al., 2018"
data_ca_or <- or(data_ca)
tt_data_ca <- table_or(analysis = data_ca_or, nstudies = 2, 
                    int = "Invasive", comp = "Non-invasive",
                    outcome = 'Ca 19-9 > 37')

# Calcification
data2 <- read.xlsx("Calcification.xlsx")
data_calc <- data2[,-9] 
names(data_calc) <- c("author", "int", "comp", "outcome", "n1", "n2", "e1", "e2")
data_calc$author[1] <- "Keane., et al., 2018"
data_calc$author[2] <- "Crippa, et.al., 2008"
data_calc_or <- or(data_calc)
tt_data_calc <- table_or(analysis = data_calc_or, nstudies = 2, 
                    int = "Invasive", comp = "Non-invasive",
                    outcome = 'Calcification')

# Mural nodules
data3 <- read.xlsx("Mural nodules.xlsx")
data_mu <- data3[,-9]
names(data_mu) <- c("author", "int", "comp", "outcome", "n1", "n2", "e1", "e2")
data_mu$author[1] <- "Crippa, et.al., 2008"
data_mu$author[2] <- "Yamao, K., et al., 2011"
data_mu$author[4] <- "Jang, K. T., et al., 2015"
data_mu$author[5] <- "Keane., et al., 2018"
data_mu_or <- or(data_mu)
tt_data_mu <- table_or(analysis = data_mu_or, nstudies = 5, 
                    int = "Invasive", comp = "Non-invasive",
                    outcome = 'Mural nodules')
```

<details>

<summary><b>Figure A -</b> Dichotomous data analysis: Odds Ratio (OR) 95%CI </summary>

<br>
```{r dic_graph, echo=FALSE, fig.height=5.9, fig.width=13.18, message=FALSE, warning=FALSE}
title_or <- c('', paste0('Invasive (n/N)'),
            paste0('Non-invasive (n/N)'),
            paste0('Odds Ratio (OR) 95%CI'), 
            paste0('Weights'))

sub_dic1 <- c('Ca 19-9 > 37', rep(NA, 6))
sub_dic2 <- c('Calcification', rep(NA, 6))
sub_dic3 <- c('Mural nodules', rep(NA, 9))

subtotal1 <- rbind(title_or, NA,
                   sub_dic1, tt_data_ca$b[-c(1:3, nrow(tt_data_ca$b)-3),], NA,
                   sub_dic2, tt_data_calc$b[-c(1:3, nrow(tt_data_calc$b)-3),], NA,
                   sub_dic3, tt_data_mu$b[-c(1:3, nrow(tt_data_mu$b)-3),])
subtotal1 <- as.matrix(subtotal1)

sizes_dic <- c(rep(NA,3), 0.008*(data_ca_or$pre$weights),1,
                rep(NA, 4), 0.02*(data_calc_or$pre$weights),1,
                rep(NA, 4), 0.008*(data_mu_or$pre$weights),1, NA, NA)
              
subtotal1_summary <- c(T, F, 
                           T, rep(F, nrow(tt_data_ca$b[-c(1:3, nrow(tt_data_ca$b)-3),])-3),T,T,F,F,
                           T, rep(F, nrow(tt_data_calc$b[-c(1:3, nrow(tt_data_calc$b)-3),])-3), T, T,F,F,
                           T, rep(F, nrow(tt_data_mu$b[-c(1:3, nrow(tt_data_mu$b)-3),])-3),T,T, F)
                           
subtotal1n <- rbind(NA,NA,
                    NA, tt_data_ca$c[-c(1:3, nrow(tt_data_ca$c)-3),], NA,
                   NA, tt_data_calc$c[-c(1:3, nrow(tt_data_calc$c)-3),], NA,
                   NA, tt_data_mu$c[-c(1:3, nrow(tt_data_mu$c)-3),])


plot_dic <- forestplot(subtotal1,
             graph.pos = 4,
             zero = 1,
             subtotal1n,
             new_page = TRUE,
             colgap = unit(5, "mm"),
             hrzl_lines = list("2" = gpar (lwd=1, columns=1:6, col="black")),
             lineheight=unit(0.7,'cm'),
             boxsize = sizes_dic,
             line.margin = 2,
             is.summary = subtotal1_summary,
             align = c('l', rep('c', 2), 'l', 'l'),
             ci.vertices = TRUE,
             txt_gp = fpTxtGp(label =gpar (cex=0.9), 
                              ticks = gpar(cex = 0.9, fontface="bold"),
                              summary = gpar(cex = 0.9),
                              xlab = gpar(cex=0.9)),
             xticks = log(c(0.5,1,3,15,30)),
             xlog=T,
             clip = c(0.5,30),
             grid = c(0.5,3,15,30),
             lwd.xaxis = 1,
             lwd.ci = 2.2,
             lwd.zero = 2,
             graphwidth = unit(10,"cm"),
             col=fpColors(box="black",line="grey", zero = 'dodgerblue4', axes="grey20", summary="black"))

plot_dic

```

</details>

